Repository dhis2/maintenance-app, pull requests merged in 2020-04, with the labels that each got.

#1092 fix(data-entry-form): remove DataElement from sections when removed from stage
  src/EditModel/event-program/assign-data-elements/epics.js
Labels: 2.31

#1091 fix(data-entry-form): remove DataElement from sections when removed from stage
  src/EditModel/event-program/assign-data-elements/epics.js
Labels: 2.32

#1090 fix(data-entry-form): remove DataElement from sections when removed from stage
  src/EditModel/event-program/assign-data-elements/epics.js
Labels: 2.33

#1089 fix(data-entry-form): remove DataElement from sections when removed from stage
  src/EditModel/event-program/assign-data-elements/epics.js
Labels: 2.34

#1107 fix(program-rule-action): remove date-to-send-message field (v33)
  src/config/field-overrides/program-rules/programRuleActionTypes.js
Labels: 2.33

#1108 fix(program-rule-action): remove date-to-send-message field (v32)
  src/config/field-overrides/program-rules/programRuleActionTypes.js
Labels: 2.32

#1109 fix(program-rule-action): remove date-to-send-message field (v31)
  src/config/field-overrides/program-rules/programRuleActionTypes.js
Labels: 2.31

#1118 fix(data-entry-form): regression for programStageDataElement removal
  src/EditModel/event-program/assign-data-elements/epics.js
Labels: 2.33

#1121 fix(data-entry-form): regression for programStageDataElement removal
  src/EditModel/event-program/assign-data-elements/epics.js
Labels: 2.31

#1120 fix(data-entry-form): regression for programStageDataElement removal
  src/EditModel/event-program/assign-data-elements/epics.js
Labels: 2.32
