Repository dhis2/maintenance-app, pull requests merged in 2023-09, with the labels that each got.

#2682 fix: update invalid email text [DHIS2-15416] v38
  src/i18n/i18n_module_en.properties
Labels: backport, 2.38

#2681 fix: update invalid email text [DHIS2-15416] v39
  src/i18n/i18n_module_en.properties
Labels: backport, 2.39

#2687 fix(expressionmanager): add overflow to description
  src/EditModel/expression/ExpressionManager.js
Labels: 2.40

#2686 fix(expressionmanager): add overflow to description
  src/EditModel/expression/ExpressionManager.js
Labels: 2.39

#2685 fix(expressionmanager): add overflow to description
  src/EditModel/expression/ExpressionManager.js
Labels: 2.38

#2684 fix(expressionmanager): add overflow to description
  src/EditModel/expression/ExpressionManager.js
Labels: 2.37
