Repository dhis2/maintenance-app, pull requests merged in 2023-04, with the labels that each got.

#2466 fix: use en as default for localeCompare
  src/EditModel/option-set/OptionSorter/optionSorter.js
Labels: backport, 2.40

#2465 fix: use en as default for localeCompare
  src/EditModel/option-set/OptionSorter/optionSorter.js
Labels: backport, 2.39

#2464 fix: use en as default for localeCompare
  src/EditModel/option-set/OptionSorter/optionSorter.js
Labels: backport, 2.38

#2463 fix: use en as default for localeCompare
  src/EditModel/option-set/OptionSorter/optionSorter.js
Labels: backport, 2.37

#2472 fix(programindicators): default period boundary
  src/config/field-config/field-defaults.js
  src/config/field-rules.js
Labels: backport, 2.40.0

#2469 fix(programindicators): default period boundary
  src/config/field-config/field-defaults.js
  src/config/field-rules.js
Labels: backport, 2.38

#2470 fix(programindicators): default period boundary
  src/config/field-config/field-defaults.js
  src/config/field-rules.js
Labels: backport, 2.39, ...''''

#2471 fix(programindicators): default period boundary
  src/config/field-config/field-defaults.js
  src/config/field-rules.js
Labels: backport, 2.40
