Repository dhis2/maintenance-app, pull requests merged in 2023-12, with the labels that each got.

#2749 fix: fix crash when instance url contains api
  package.json
  yarn.lock
Labels: 2.40

#2748 fix: fix crash when instance url contains api
  package.json
  yarn.lock
Labels: 2.39

#2751 fix: add in missing cache translation strings [DHIS2-15940] (#2715)
  src/i18n/i18n_module_en.properties
Labels: backport, 2.40

#2752 fix: add in missing cache translation strings [DHIS2-15940] (v39)
  src/i18n/i18n_module_en.properties
Labels: backport, 2.39

#2753 fix: add in missing cache translation strings [DHIS2-15940] (v38)
  src/i18n/i18n_module_en.properties
Labels: backport, 2.38

#2731 fix(programrules): make static text fullwidth
  src/config/field-overrides/program-rules/programRuleActionDialog.component.js
Labels: 2.40

#2754 fix(programrules): make static text fullwidth
  src/config/field-overrides/program-rules/programRuleActionDialog.component.js
Labels: 2.39

#2755 fix(programrules): make static text fullwidth
  src/config/field-overrides/program-rules/programRuleActionDialog.component.js
Labels: 2.38

#2761 fix(indicator-group): add description field
  src/config/field-config/field-order.js
Labels: 2.40

#2762 fix(indicator-group): add description field
  src/config/field-config/field-order.js
Labels: 2.39

#2763 fix(indicator-group): add description field
  src/config/field-config/field-order.js
Labels: 2.38

#2757 fix(trackedEntityType): fix cloning tet with attributes
  src/EditModel/SingleModelStore.js
Labels: 2.39

#2758 fix(trackedEntityType): fix cloning tet with attributes
  src/EditModel/SingleModelStore.js
Labels: 2.40

#2759 fix(trackedEntityType): fix cloning tet with attributes
  src/EditModel/SingleModelStore.js
Labels: 2.38

#2764 fix: add missing translations and clean custom columns (#2447)
  src/List/columns/ColumnConfigDialog.js
  src/i18n/i18n_module_en.properties
Labels: 2.39

#2765 fix: add missing translations and clean custom columns (#2447)
  src/List/columns/ColumnConfigDialog.js
  src/i18n/i18n_module_en.properties
Labels: 2.38

#2769 fix(text-field): fix error message when field is multiline
  src/forms/form-fields/text-field.js
  src/i18n/i18n_module_en.properties
Labels: 2.38

#2768 fix(text-field): fix error message when field is multiline
  src/forms/form-fields/text-field.js
  src/i18n/i18n_module_en.properties
Labels: 2.39

#2767 fix(text-field): fix error message when field is multiline
  src/forms/form-fields/text-field.js
  src/i18n/i18n_module_en.properties
Labels: 2.40

#2774 fix: fix crash when instance url contains api
  package.json
  yarn.lock
Labels: 2.38

#2772 fix(progam-rule): rename hide program stage action
  src/config/field-overrides/program-rules/programRuleActionTypes.js
  src/i18n/i18n_module_en.properties
Labels: 2.38

#2773 fix(programrule): rename program stage to hide label
  src/config/field-overrides/program-rules/programRuleActionTypes.js
Labels: 2.40

#2391 fix(programrule): rename hide program stage action
  src/config/field-overrides/program-rules/programRuleActionTypes.js
  src/i18n/i18n_module_en.properties
Labels: backport, 2.39
